component:
  name: Test
  version: 1.0.0
  type: service

dependencies:
  - name: mongodb
    type: database
    version: latest
  - name: express
    type: framework
    version: latest

environment:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: 3000

build:
  language: nodejs
  version: 14

run:
  command: nodemon index.js
